-- SQL Migration for API Keys Table
-- Run this in the Supabase SQL Editor

-- Create the api_keys table
CREATE TABLE IF NOT EXISTS public.api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    key_hash TEXT NOT NULL UNIQUE,
    prefix TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_used TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true NOT NULL
);

-- Enable RLS
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- Create policies (only allow users to see/revoke their own keys)
-- Create policies (only allow users to see/revoke their own keys)
-- Note: These policies assume Supabase Auth is linked to public.users via email
-- Adjust if you use a different link (like auth_user_id UUID)
CREATE POLICY "Users can view their own API keys"
ON public.api_keys FOR SELECT
USING (EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = user_id AND email = auth.jwt() ->> 'email'
));

CREATE POLICY "Users can revoke their own API keys"
ON public.api_keys FOR UPDATE
USING (EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = user_id AND email = auth.jwt() ->> 'email'
));

-- Index for fast lookup by hash (used during authentication per request)
CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON public.api_keys(key_hash);
CREATE INDEX IF NOT EXISTS idx_api_keys_user_id ON public.api_keys(user_id);
