-- SQL Migration for API Keys Table
-- Run this in the Supabase SQL Editor

-- Create the api_keys table
CREATE TABLE IF NOT EXISTS public.api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    key_hash TEXT NOT NULL UNIQUE,
    prefix TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_used TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true NOT NULL
);

-- Enable RLS
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- RLS Policies
-- ============================================================
-- NOTE: The backend uses SUPABASE_SERVICE_ROLE_KEY which bypasses
-- RLS entirely. These policies are only relevant if you also
-- query the table through the Supabase anon/authenticated client.
-- ============================================================

-- Allow users to view their own API keys
CREATE POLICY "Users can view their own API keys"
ON public.api_keys FOR SELECT
USING (EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = user_id AND email = auth.jwt() ->> 'email'
));

-- Allow users to create their own API keys
CREATE POLICY "Users can create their own API keys"
ON public.api_keys FOR INSERT
WITH CHECK (EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = user_id AND email = auth.jwt() ->> 'email'
));

-- Allow users to update (revoke) their own API keys
CREATE POLICY "Users can revoke their own API keys"
ON public.api_keys FOR UPDATE
USING (EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = user_id AND email = auth.jwt() ->> 'email'
));

-- Allow users to delete their own API keys
CREATE POLICY "Users can delete their own API keys"
ON public.api_keys FOR DELETE
USING (EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = user_id AND email = auth.jwt() ->> 'email'
));

-- Index for fast lookup by hash (used during authentication per request)
CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON public.api_keys(key_hash);
CREATE INDEX IF NOT EXISTS idx_api_keys_user_id ON public.api_keys(user_id);

