'use client';

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Lock, Eye, FileText } from 'lucide-react';
import { useState, useEffect } from 'react';

export default function PrivacyPage() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  return (
    <div className="bg-[#f9f9f9] min-h-screen flex flex-col selection:bg-[#775a19]/10 selection:text-[#4e3700]">
      <Navbar />

      <main className="max-w-4xl mx-auto py-24 px-6 md:px-20 space-y-16 flex-grow w-full">
        <div className={`space-y-4 ${mounted ? 'animate-in' : 'opacity-0'}`}>
          <p className="text-[11px] font-bold text-[#775a19] mb-4 tracking-[0.3em] uppercase">LEGAL</p>
          <h1 className="text-5xl font-normal text-[#1a1c1c] tracking-tight leading-tight">Privacy <span className="italic font-light text-[#4e3700]">Policy</span></h1>
          <p className="text-[#d1c5b4] font-mono text-[10px] uppercase tracking-widest">Last Updated: May 20, 2026</p>
        </div>

        <div className="space-y-16 pt-8">
          <PrivacySection 
            icon={Lock} 
            title="Data Sovereignty" 
            content="At Seka Kama, we believe in the sovereignty of ecological data. All conservancy-specific datasets uploaded for simulation purposes remain the property of the respective management units. We do not sell or share granular spatial data with third parties."
            delay="100ms"
          />

          <PrivacySection 
            icon={Eye} 
            title="User Analytics" 
            content="We collect minimal usage telemetry to improve our digital twin algorithms. This includes anonymized interaction data with the map interface and simulation tool usage statistics. We utilize privacy-first analytics providers to ensure no personally identifiable information is tracked."
            delay="200ms"
          />

          <PrivacySection 
            icon={FileText} 
            title="Ethical AI Usage" 
            content="The narratives generated by our LLM integration are strictly for research and conservation planning. Results should not be used as the sole basis for legal or destructive environmental decisions without field verification by certified ecologists."
            delay="300ms"
          />
        </div>

        <div className={`pt-16 border-t border-[#d1c5b4]/60 ${mounted ? 'animate-in' : 'opacity-0'}`} style={{ animationDelay: '400ms', animationFillMode: 'both' }}>
          <p className="text-sm text-[#4e4639] font-light italic">
            If you have concerns regarding data usage or wish to request data deletion, please contact our
            Data Operations lead at <span className="text-[#775a19] font-bold border-b border-[#775a19]">jasemwaura@gmail.com</span>.
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
}

function PrivacySection({ icon: Icon, title, content, delay }: { icon: any, title: string, content: string, delay: string }) {
  return (
    <section className={`space-y-6 animate-in`} style={{ animationDelay: delay, animationFillMode: 'both' }}>
      <div className="flex items-center gap-4 text-[#775a19]">
        <Icon className="w-6 h-6" />
        <h2 className="text-2xl font-serif font-medium tracking-tight text-[#1a1c1c]">{title}</h2>
      </div>
      <p className="text-[#4e4639] leading-relaxed font-light text-base max-w-3xl">
        {content}
      </p>
    </section>
  );
}
